// Originally generated by ChatGPT 4.0 and refactored by Sam Siewert
//
// Match the style of hello_riemann and hello_simpson
//
#include <iostream>
#include <cmath>
#include <mpi.h>
#include <time.h>
//#define RANGE (M_PI)
#define RANGE (100000) //f(x) = 10
#define STEPS (100000000) // updated step count for higher precision 
#define DX (0.001)
using namespace std;

int thread_count=1;

double function_to_integrate(double x);

using namespace std;

double trapezoidal_rule(double a, double b, int n) 
{
    double h = (b - a) / n;
    double sum = (function_to_integrate(a) + function_to_integrate(b)) / 2.0;

#pragma omp parallel for num_threads(thread_count) reduction(+:sum)
    for (int i = 1; i < n; i++) 
    {
        double x = a + i * h;
        sum += function_to_integrate(x);
    }

    return h * sum;
}

int main(int argc, char* argv[]) 
{

    int my_rank, comm_sz;
    //MPI initialization 
    MPI_Init(NULL,NULL);
    MPI_Comm_size(MPI_COMM_WORLD, &comm_sz);
    MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);

    const double a = 0.0;
    const double b = RANGE;
    const int n = (b-a)/DX; // total steps = stop - start / step size

    int local_n = n / comm_sz; // # of steps for each process

    //starting and stop points for each process
    double local_a = my_rank * local_n * DX;
    double local_b = local_a + local_n * DX;
  
   double fstart, fnow;
   struct timespec start, now;
   clock_gettime(CLOCK_MONOTONIC, &start);
   fstart = (double)start.tv_sec  + (double)start.tv_nsec / 1000000000.0;

   clock_gettime(CLOCK_MONOTONIC, &now);
   fnow = (double)now.tv_sec  + (double)now.tv_nsec / 1000000000.0;
   printf("\nstart test at %lf\n", fnow-fstart);


    double local_integation = trapezoidal_rule(local_a, local_b, local_n);

    double total_integration = 0;

    MPI_Reduce(&local_integation,&total_integration,1,MPI_DOUBLE,MPI_SUM,0,MPI_COMM_WORLD);

    if(my_rank == 0)
    {
        cout.precision(15);
        cout << "The integral of f(x) from 0.0 to " << b << " with " << n << " steps is " << total_integration << endl;
    }
    clock_gettime(CLOCK_MONOTONIC, &now);
    fnow = (double)now.tv_sec  + (double)now.tv_nsec / 1000000000.0;
    printf("stop test at %lf\n", fnow-fstart);

    MPI_Finalize();
      return 0;
}

double function_to_integrate(double x)
{
    return 10.0;
    //return (sin(x));
}
